name: Output Information Issues
on:
  issues:
    
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub context
              run: echo "Issue body => ${{ toJson(github.event) }}"