name: Output Information Issues
on:
  issues:
    types: [opened, edited, closed]
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub context
              run: echo "${{ toJson(github) }}"